todoapp/todo/urls.py
from django.urls import path

from . import views

app_name = "todo"
urlpatterns = [
	path('', views.index, name='index'),
	path('todolist/', views.addTodo, name='addTodo'),
	path('todolist/markascomplete/<int:item_id>', views.markAsComplete, name='markAsComplete'),
	path('todolist/deleteTodoItem/<int:item_id>', views.deleteTodoItem, name='deleteTodoItem'),
]

todoapp/todoapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls')),
]

todoapp/todo/models.py
from django.db import models

# Create your models here.
from django.db import models

class Todo(models.Model):
	item_name = models.CharField(max_length=255)
	item_status = models.CharField(max_length=20)
	created_date = models.DateTimeField('date created')

	def __str__(self):
		return self.item_name

todoapp/todo/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from .models import Todo
from django.utils import timezone

def index(request):
	todo_list = Todo.objects.all()
	context = { 'todo_list': todo_list }
	return render(request, 'todo/index.html', context)

def addTodo(request):
	add_todo = request.POST.get('add_todo_name', None)
	current_date = timezone.now()
	new_todo_item = Todo(item_name=add_todo, item_status="new", created_date=current_date)
	new_todo_item.save()
	return HttpResponseRedirect(reverse('todo:index'))

def markAsComplete(request, item_id):
	item = Todo.objects.get(pk=item_id)
	item.item_status = 'done'
	item.save()
	return HttpResponseRedirect(reverse('todo:index'))

def deleteTodoItem(request, item_id):
	print('delete: ', item_id)
	item = Todo.objects.get(pk=item_id)
	item.delete()
	return HttpResponseRedirect(reverse('todo:index'))

todoapp/todo/templates/layouts.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie-edge">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<title>Polls {% block title %} {% endblock %}</title>
</head>
<body>
	{% include 'partials/_navbar.html' %}
	<div class="container">
		<div class="row">
			<div class="col-md-12 m-auto">
				{% block content %} {% endblock %}
			</div>
		</div>
	</div>
</body>
</html>

todoapp/todo/templates/partials/_navbar.html
<nav class="navbar navbar-dark bg-info mb-4">
	<div class="container">
		<a href="/" class="navbar-brand">To Do List</a>
	</div>
</nav>

todoapp/todo/templates/todo/index.html
{% extends 'layouts.html' %}

{% block content %}
	<form action="{% url 'todo:addTodo' %}" method="post">
		{% csrf_token %}
		<div class="form-group">
			<label for="exampleInputEmail1">To Do</label>
			<input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="enter to do list" name="add_todo_name" value="{{ todo_name }}">
		</div>
		<input type="submit" name="" value="Save">
	</form>
	<br>
	<ul class="list-group">
		{% for item in todo_list %}
			<li class="list-group-item">
				<div class="d-flex flex-row">
					<div class="d-flex flex-column flex-grow-1">
						<p class="m-0">{{ item.item_name }}</p>
						<small>{{ item.created_date }}</small>
					</div>
					{% if item.item_status == 'new' %}
						<a href="{% url 'todo:markAsComplete' item.id %}" class="btn btn-primary btn-sm my-auto mr-3">mark as complete</a>
						<span class="badge badge-primary float-right my-auto">{{ item.item_status }}</span>
					{% else %}
						<span class="badge badge-success float-right my-auto">{{ item.item_status }}</span>
					{% endif %}
					<a href="{% url 'todo:deleteTodoItem' item.id %}" class="my-auto ml-3"><i class="fa fa-trash-o my-auto"></i></a>
				</div>
			</li>
		{% endfor %}
	</ul>
{% endblock %}